name = "colorbook-backend-worldfrees"
main = "src/index.ts"
compatibility_date = "2024-11-12"

# Environment variables (non-sensitive)
[vars]
S3_BUCKET = "colorbook"
SHOPIFY_DOMAIN = "e76594-67.myshopify.com"
BACKEND_URL = "https://colorbook-backend-worldfrees.3dworldjames.workers.dev"
WEBHOOK_URL = "https://colorbook-backend-worldfrees.3dworldjames.workers.dev/webhooks/shopify/orders/paid"
PERSONAL_DOMAIN = "free1mind.com"
SHOPIFY_STOREFRONT_TOKEN = "64b1058926b92710a97b8dadbcfff10d"
SHOPIFY_VARIANT_GID = "gid://shopify/ProductVariant/50288087105826"

# Secrets (these should be set using: wrangler secret put SECRET_NAME)
# The following secrets need to be set in Cloudflare:
# - STABILITY_API_KEY
# - SHOPIFY_WEBHOOK_SECRET
# - SHOPIFY_STOREFRONT_TOKEN
# - SHOPIFY_ADMIN_TOKEN
# - LULU_API_KEY
# - LULU_CLIENT_SECRET

# KV namespace for storing design and customer data
[[kv_namespaces]]
binding = "COLORBOOK_KV"
id = "f07df84cd5a5418e8c7f4fc0dd527011"
preview_id = "9ba8d789785b427f9c956e057aed0ffc"

# R2 bucket for image storage
[[r2_buckets]]
binding = "COLORBOOK_R2"
bucket_name = "colorbook-images"
