name = "colorbook-backend"
main = "src/index.ts"
compatibility_date = "2024-11-12"

[vars]
OPENAI_API_KEY = ""
STABILITY_API_KEY = ""
SHOPIFY_WEBHOOK_SECRET = ""
LULU_API_KEY = ""
LULU_CLIENT_SECRET = ""
S3_BUCKET = "colorbook"
